apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: graceful-euler-c1b10e8a0a-hc
  namespace: apps-release
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 7070
        requestPath: /docs
  targetRef:
    group: ""
    kind: Service
    name: graceful-euler-c1b10e8a0a-srv
